name: "Old firmaware Proxy addon"
description: "Create a proxy for old meteostation firmwares."
version: "0.0.2"
slug: "ofw_proxy"
url: "https://github.com/schizza/OFWProxy-addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  80/tcp: 80

options:
  host_name: "homeassistant.local"
  host_ip: ""
  ha_port: 8123
  cert_valid_for: 65535
  auto_recreate_cert: false

schema:
  host_name: str
  host_ip: str
  ha_port: int
  cert_valid_for: int
  auto_recreate_cert: bool
